pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
revision:
max_train_samples:
cache_dir:
seed: 42
center_crop: false
random_flip: false
logging_dir: logs
mixed_precision: bf16
report_to: tensorboard
local_rank: -1
max_train_steps:
gradient_checkpointing: false
train_data_dir: datasets\person
output_dir: exps_domainnet/prompt_d_quickdraw_multiclient
resolution: 512
model_type: MLP
model_dir:
pretrained: false
train_batch_size: 4
gradient_accumulation_steps: 1
num_train_epochs: 50
num_shot: 16
select: random
num_workers: 0
learning_rate: 0.1
scale_lr: false
lr_scheduler: constant
lr_warmup_steps: 0
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0
adam_epsilon: 1e-08
max_grad_norm: 1.0
start_idx: 0
end_idx: 0
skip_evaluation: false
log_every_steps: 50
log_every_epochs: 5
save_steps:
num_epochs: 50
prompt: ''
template_key: '0'
concept:
clip_attributes:
num_test_samples: 2
original_sd: false
interpolate_type: ''
interpolate_steps:
evaluation_type: generate
image_dir: images
prompt_file:
src_img_dir:
gen_img_dir:
kid_subset_size: 1000
use_sld: false
use_esd: false
negative_prompt:
scheduler: pndm
num_inference_steps: 50
fp16: false
client_num: 1
domain: quickdraw
train_type: prompt
test_type:
dataset: domainnet
domains:
- clipart
- infograph
- painting
- quickdraw
- real
- sketch
categories:
- airplane
- axe
- basketball
- bicycle
- bird
- bracelet
- clock
- flower
- pizza
- strawberry
